"""
Comprehensive integration tests for preprimer end-to-end functionality.
"""

import shutil
import tempfile
from pathlib import Path

import pytest

from preprimer.core.converter import PrimerConverter
from preprimer.core.enhanced_config import EnhancedConfig
from preprimer.core.exceptions import ParserError, PrePrimerError, ValidationError
from preprimer.core.registry import ParserRegistry
from preprimer.parsers.artic_parser import ARTICParser
from preprimer.parsers.varvamp_parser import VarVAMPParser


class TestEndToEndWorkflows:
    """Test complete end-to-end workflows."""

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace for testing."""
        workspace = Path(tempfile.mkdtemp())
        yield workspace
        shutil.rmtree(workspace)

    @pytest.fixture
    def varvamp_test_file(self, temp_workspace):
        """Create a test VarVAMP file."""
        content = """amplicon_name	amplicon_length	primer_name	pool	start	stop	seq	size	gc_best	temp_best	mean_gc	mean_temp	score
SARS-CoV-2_1	298	FW_SARS-CoV-2_1_1	1	30	54	GTTTACAGGAAACACCAGACAGAA	24	0.42	56.8	0.42	56.8	95.7
SARS-CoV-2_1	298	RW_SARS-CoV-2_1_1	1	327	351	TCAGGCAAGGATGTGTTGTAGATGA	25	0.44	58.2	0.44	58.2	94.3
SARS-CoV-2_2	312	FW_SARS-CoV-2_2_1	2	320	344	GCTTGTGCAAAGAATAAGTGACACA	25	0.40	57.5	0.40	57.5	92.1
SARS-CoV-2_2	312	RW_SARS-CoV-2_2_1	2	631	655	GACAGGAAGGATAGAAGCCAGGTAT	25	0.48	58.9	0.48	58.9	91.8
SARS-CoV-2_3	289	FW_SARS-CoV-2_3_1	1	610	634	TCAAGAAAACCAGGAGGGAAGTTTA	25	0.40	57.2	0.40	57.2	93.5
SARS-CoV-2_3	289	RW_SARS-CoV-2_3_1	1	898	922	TGGAGTAACATAGGTCTGCATGGTA	25	0.44	58.4	0.44	58.4	92.7"""

        file_path = temp_workspace / "test_varvamp.tsv"
        file_path.write_text(content)
        return file_path

    @pytest.fixture
    def artic_test_file(self, temp_workspace):
        """Create a test ARTIC file."""
        content = """MN908947.3	30	54	nCoV-2019_400_1_LEFT_1	1	+	GTTTACAGGAAACACCAGACAGAA
MN908947.3	385	410	nCoV-2019_400_1_RIGHT_1	1	-	TCATCTGGACTCTGGAGGAGGCCC
MN908947.3	320	342	nCoV-2019_400_2_LEFT_1	2	+	CCAGGTAACAAACCAACCAACTTT
MN908947.3	704	726	nCoV-2019_400_2_RIGHT_1	2	-	ACTGAGGGAGCCTTGAATACACC
MN908947.3	642	664	nCoV-2019_400_3_LEFT_1	1	+	CACCAACCAACTTTCGATCTCTTG
MN908947.3	1004	1028	nCoV-2019_400_3_RIGHT_1	1	-	TTGTAGTGCTGAAGGCCATAGCTG"""

        file_path = temp_workspace / "test_artic.bed"
        file_path.write_text(content)
        return file_path

    @pytest.fixture
    def reference_file(self, temp_workspace):
        """Create a reference sequence file."""
        content = """>MN908947.3 SARS-CoV-2 reference
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACTCGAAGGCATTCAGTACGGTCGTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGGCGAAATACCAGTGGCTTACCGCAAGGTTCTTCTTCGTAAGAACGGTAATAAAGGAGCTGGTGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTAGGCGACGAGCTTGGCACTGATCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTGTTACCCGTGAACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGGCCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTCATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCGTGAACATGAGCATGAAATTGCTTGGTACACGGAACGTTCTGAAAAGAGCTATGAATTGCAGACACCTTTTGAAATTAAATTGGCAAAGAAATTTGACACCTTCAATGGGGAATGTCCAAATTTTGTATTTCCCTTAAATTCCATAATCAAGACTATTCAACCAAGGGTTGAAAAGAAAAAGCTTGATGGCTTTATGGGTAGAATTCGATCTGTCTATCCAGTTGCGTCACCAAATGAATGCAACCAAATGTGCCTTTCAACTCTCATGAAGTGTGATCATTGTGGTGAAACTTCATGGCAGACGGGCGATTTTGTTAAAGCCACTTGCGAATTTTGTGGCACTGAGAATTTGACTAAAGAAGGTGCCACTACTTGTGGTTACTTACCCCAAAATGCTGTTGTTAAAATTTATTGTCCAGCATGTCACAATTCAGAAGTAGGACCTGAGCATAGTCTTGCCGAATACCATAATGAATCTGGCTTGAAAACCATTCTTCGTAAGGGTGGTCGCACTATTGCCTTTGGAGGCTGTGTGTTCTCTTATGTTGGTTGCCATAACAAGTGTGCCTATTGGGTTCCACGTGCTAGCGCTAACATAGGTTGTAACCATACAGGTGTTGTTGGAGAAGGTTCCGAAGGTCTTAATGACAACCTTCTTGAAATACTCCAAAAAGAGAAAGTCAACATCAATATTGTTGGTGACTTTAAACTTAATGAAGAGATCGCCATTATTTTGGCATCTTTTTCTGCTTCCACAAGTGCTTTTGTGGAAACTGTGAAAGGTTTGGATTATAAAGCATTCAAACAAATTGTTGAATCCTGTGGTAATTTTAAAGTTACAAAAGGAAAAGCTAAAAAAGGTGCCTGGAATATTGGTGAACAGAAATCAATACTGAGTCCTCTTTATGCATTTGCATCAGAGGCTGCTCGTGTTGTACGATCAATTTTCTCCCGCACTCTTGAAACTGCTCAAAATTCTGTGCGTGTTTTACAGAAGGCCGCTATAACAATACTAGATGGAATTTCACAGTATTCACTGAGACTCATTGATGCTATGATGTTCACATCTGATTTGGCTACTAACAATCTAGTTGTAATGGCCTACATTACAGGTGGTGTTGTTCAGTTGACTTCGCAGTGGCTAACTAACATCTTTGGCACTGTTTATGAAAAACTCAAACCCGTCCTTGATTGGCTTGAAGAGAAGTTTAAGGAAGGTGTAGAGTTTCTTAGAGACGGTTGGGAAATTGTTAAATTTATCTCAACCTGTGCTTGTGAAATTGTCGGTGGACAAATTGTCACCTGTGCAAAGGAAATTAAGGAGAGTGTTCAGACATTCTTTAAGCTTGTAAATAAATTTTTGGCTTTGTGTGCTGACTCTATCATTATTGGTGGAGCTAAACTTAAAGCCTTGAATTTAGGTGAAACATTTGTCACGCACTCAAAGGGATTGTACAGAAAGTGTGTTAAATCCAGAGAAGAAACTGGCCTACTCATGCCTCTAAAAGCCCCAAAAGAAATTATCTTCTTAGAGGGAGAAACACTTCCCACAGAAGTGTTAACAGAGGAAGTTGTCTTGAAAACTGGTGATTTACAACCATTAGAACAACCTACTAGTGAAGCTGTTGAAGCTCCATTGGTTGGTACACCAGTTTGTATTAACGGGCTTATGTTGCTCGAAATCAAAGACACAGAAAAGTACTGTGCCCTTGCACCTAATATGATGGTAACAAACAATACCTTCACACTCAAAGGCGGTGCACCAACAAAGGTTACTTTTGGTGATGACACTGTGATAGAAGTGCAAGGTTACAAGAGTGTGAATATCACTTTTGAACTTGATGAAAGGATTGATAAAGTACTTAATGAGAAGTGCTCTGCCTATACAGTTGAACTCGGTACAGAAGTAAATGAGTTCGCCTGTGTTGTGGCAGATGCTGTCATAAAAACTTTGCAACCAGTATCTGAATTACTTACACCACTGGGCATTGATTTAGATGAGTGGAGTATGGCTACATACTACTTATTTGATGAGTCTGGTGAGTTTAAATTGGCTTCACATATGTATTGTTCTTTCTACCCTCCAGATGAGGATGAAGAAGAAGGTGATTGTGAAGAAGAAGAGTTTGAGCCATCAACTCAATATGAGTATGGTACTGAAGATGATTACCAAGGTAAACCTTTGGAATTTGGTGCCACTTCTGCTGCTCTTCAACCTGAAGAAGAGCAAGAAGAAGATTGGTTAGATGATGATAGTCAACAAACTGTTGGTCAACAAGACGGCAGTGAGGACAATCAGACAACTACTATTCAAACAATTGTTGAGGTTCAACCTCAATTAGAGATGGAACTTACACCAGTTGTTCAGACTATTGAAGTGAATAGTTTTAGTGGTTATTTAAAACTTACTGACAATGTATACATTAAAAATGCAGACATTGTGGAAGAAGCTAAAAAGGTAAAACCAACAGTGGTTGTTAATGCAGCCAATGTTTACCTTAAACATGGAGGAGGTGTTGCAGGAGCCTTAAATAAGGCTACTAACAATGCCATGCAAGTTGAATCTGATGATTACATAGCTACTAATGGACCACTTAAAGTGGGTGGTAGTTGTGTTTTAAGCGGACACAATCTTGCTAAACACTGTCTTCATGTTGTCGGCCCAAATGTTAACAAAGGTGAAGACATTCAACTTCTTAAGAGTGCTTATGAAAATTTTAATCAGCACGAAGTTCTACTTGCACCATTATTATCAGCTGGTATTTTTGGTGCTGACCCTATACATTCTTTAAGAGTTTGTGTAGATACTGTTCGCACAAATGTCTACTTAGCTGTCTTTGATAAAAATCTCTATGACAAACTTGTTTCAAGCTTTTTGGAAATGAAGAGTGAAAAGCAAGTTGAACAAAAGATCGCTGAGATTCCTAAAGAGGAAGTTAAGCCATTTATAACTGAAAGTAAACCTTCAGTTGAACAGAGAAAACAAGATGATAAGAAAATCAAAGCTTGTGTTGAAGAAGTTACAACAACTCTGGAAGAAACTAAGTTCCTCACAGAAAACTTGTTACTTTATATTGACATTAATGGCAATCTTCATCCAGATTCTGCCACTCTTGTTAGTGACATTGACATCACTTTCTTAAAGAAAGATGCTCCATATATAGTGGGTGATGTTGTTCAAGAGGGTGTTTTAACTGCTGTGGTTATACCTACTAAAAAGGCTGGTGGCACTACTGAAATGCTAGCGAAAGCTTTGAGAAAAGTGCCAACAGACAATTATATAACCACTTACCCGGGTCAGGGTTTAAATGGTTACACTGTAGAGGAGGCAAAGACAGTGCTTAAAAAGTGTAAAAGTGCCTTTTACATTCTACCATCTATTATCTCTAATGAGAAGCAAGAAATTCTTGGAACTGTTTCTTGGAATTTGCGAGAAATGCTTGCACATGCAGAAGAAACACGCAAATTAATGCCTGTCTGTGTGGAAACTAAAGCCATAGTTTCAACTATACAGCGTAAATATAAGGGTATTAAAATACAAGAGGGTGTGGTTGATTATGGTGCTAGATTTTACTTTTACACCAGTAAAACAACTGTAGCGTCACTTATCAACACACTTAACGATCTAAATGAAACTCTTGTTACAATGCCACTTGGCTATGTAACACATGGCTTAAATTTGGAAGAAGCTGCTCGGTATATGAGATCTCTCAAAGTGCCAGCTACCAGTTTCTGTTTCTTCACCTGATGCTGTTACAGCGTATAATGGTTATCTTACTTCTTCTTCTAAAACACCTGAAGAACATTTTATTGAAACCATCTCACTTGCTGGTTCCTATAAAGATTGGTCCTATTCTGGACAATCTACACAACTAGGTATAGAATTTCTTAAGAGAGGTGATAAAAGTGTATATTACACTAGTAATCCTACCACATTCCACCTAGATGGTGAAGTTATCACCTTTGACAATCTTAAGACACTTCTTTCTTTGAGAGAAGTGAGGACTATTAAGGTGTTTACAACAGTAGACAACATTAACCTCCACACGCAAGTTGTGGACATGTCAATGACATATGGACAACAGTTTGGTCCAACTTATTTGGATGGAGCTGATGTTACTAAAATAAAACCTCATAATTCACATGAAGGTAAAACATTTTATGTTTTACCTAATGATGACACTCTACGTGTTGAGGCTTTTGAGTACTACCACACAACTGATCCTAGTTTTCTGGGTAGGTACATGTCAGCATTAAATCACACTAAAAAGTGGAAATACCCACAAGTTAATGGTTTAACTTCTATTAAATGGGCAGATAACAACTGTTATCTTGCCACTGCATTGTTAACACTCCAACAAATAGAGTTGAAGTTTAATCCACCTGCTCTACAAGATGCTTATTACAGAGCAAGGGCTGGTGAAGCTGCTAACTTTTGTGCACTTATCTTAGCCTACTGTAATAAGACAGTAGGTGAGTTAGGTGATGTTAGAGAAACAATGAGTTACTTGTTTCAACATGCCAATTTAGATTCTTGCAAAAGAGTCTTGAACGTGGTGTGTAAAACTTGTGGACAACAGCAGACAACCCTTAAGGGTGTAGAAGCTGTTATGTACATGGGCACACTTTCTTATGAACAATTTAAGAAAGGTGTTCAGATACCTTGTACGTGTGGTAAACAAGCTACAAAATATCTAGTACAACAGGAGTCACCTTTTGTTATGATGTCAGCACCACCTGCTCAGTATGAACTTAAGCATGGTACATTTACTTGTGCTAGTGAGTACACTGGTAATTACCAGTGTGGTCACTATAAACATATAACTTCTAAAGAAACTTTGTATTGCATAGACGGTGCTTTACTTACAAAGTCCTCAGAATACAAAGGTCCTATTACGGATGTTTTCTACAAAGAAAACAGTTACACAACAACCATAAAACCAGTTACTTATAAATTGGATGGTGTTGTTTGTACAGAAATTGACCCTAAGTTGGACAATTATTATAAGAAAGACAATTCTTATTTCACAGAGCAACCAATTGATCTTGTACCAAACCAACCATATCCAAACGCAAGCTTCGATAATTTTAAGTTTGTATGTGATAATATCAAATTTGCTGATGATTTAAACCAGTTAACTGGTTATAAGAAACCTGCTTCAAGAGAGCTTAAAGTTACATTTTTCCCTGACTTAAATGGTGATGTGGTGGCTATTGATTATAAACACTACACACCCTCTTTTAAGAAAGGAGCTAAATTGTTACATAAACCTATTGTTTGGCATGTTAACAATGCAACTAATAAAGCCACGTATAAACCAAATACCTGGTGTATACGTTGTCTTTGGAGCACAAAACCAGTTGAAACATCAAATTCGTTTGATGTACTGAAGTCAGAGGACGCGCAGGGAATGGATAATCTTGCCTGCGAAGATCTAAAACCAGTCTCTGAAGAAGTAGTGGAAAATCCTACCATACAGAAAGACGTTCTTGAGTGTAATGTGAAAACTACCGAAGTTGTAGGAGACATTATACTTAAACCAGCAAATAATAGTTTAAAAATTACAGAAGAGGTTGGCCACACAGATCTAATGGCTGCTTATGTAGACAATTCTAGTCTTACTATTAAGAAACCTAATGAATTATCTAGAGTATTAGGTTTGAAAACCCTTGCTACTCATGGTTTAGCTGCTGTTAATAGTGTCCCTTGGGATACTATAGCTAATTATGCTAAGCCTTTTCTTAACAAAGTTGTTAGTACAACTACTAACATAGTTACACGGTGTTTAAACCGTGTTTGTACTAATTATATGCCTTATTTCTTTACTTTATTGCTACAATTGTGTACTTTTACTAGAAGTACAAATTCTAGAATTAAAGCATCTATGCCGACTACTATAGCAAAGAATACTGTTAAGAGTGTCGGTAAATTTTGTCTAGAGGCTTCATTTAATTATTTGAAGTCACCTAATTTTTCTAAACTGATAAATATTATAATTTGGTTTTTACTATTAAGTGTTTGCCTAGGTTCTTTAATCTACTCAACCGCTGCTTTAGGTGTTTTAATGTCTAATTTAGGCATGCCTTCTTACTGTACTGGTTACAGAGAAGGCTATTTGAACTCTACTAATGTCACTATTGCAACCTACTGTACTGGTTCTATACCTTGTAGTGTTTGTCTTAGTGGTTTAGATTCTTTAGACACCTATCCTTCTTTAGAAACTATACAAATTACCATTTCATCTTTTAAATGGGATTTAACTGCTTTTGGCTTAGTTGCAGAGTGGTTTTTGGCATATATTCTTTTCACTAGGTTTTTCTATGTACTTGGATTGGCTGCAATCATGCAATTGTTTTTCAGCTATTTTGCAGTACATTTTATTAGTAATTCTTGGCTTATGTGGTTAATAATTAATCTTGTACAAATGGCCCCGATTTCAGCTATGGTTAGAATGTACATCTTCTTTGCATCATTTTATTATGTATGGAAAAGTTATGTGCATGTTGTAGACGGTTGTAATTCATCAACTTGTATGATGTGTTACAAACGTAATAGAGCAACAAGAGTCGAATGTACAACTATTGTTAATGGTGTTAGAAGGTCCTTTTATGTCTATGCTAATGGAGGTAAAGGCTTTTGCAAACTACACAATTGGAATTGTGTTAATTGTGATACATTCTGTGCTGGTAGTACATTTATTAGTGATGAAGTTGCGAGAGACTTGTCACTACAGTTTAAAAGACCAATAAATCCTACTGACCAGTCTTCTTACATCGTTGATAGTGTTACAGTGAAGAATGGTTCCATCCATCTTTACTTTGATAAAGCTGGTCAAAAGACTTATGAAAGACATTCTCTCTCTCATTTTGTTAACTTAGACAACCTGAGAGCTAATAACACTAAAGGTTCATTGCCTATTAATGTTATAGTTTTTGATGGTAAATCAAAATGTGAAGAATCATCTGCAAAATCAGCGTCTGTTTACTACAGTCAGCTTATGTGTCAACCTATACTGTTACTAGATCAGGCATTAGTGTCTGATGTTGGTGATAGTGCGGAAGTTGCAGTTAAAATGTTTGATGCTTACGTTAATACGTTTTCATCAACTTTTAACGTACCAATGGAAAAACTCAAAACACTAGTTGCAACTGCAGAAGCTGAACTTGCAAAGAATGTGTCCTTAGACAATGTCTTATCTACTTTTATTTCAGCAGCTCGGCAAGGGTTTGTTGATTCAGATGTAGAAACTAAAGATGTTGTTGAATGTCTTAAATTGTCACATCAATCTGACATAGAAGTTACTGGCGATAGTTGTAATAACTATATGCTCACCTATAACAAAGTTGAAAACATGACACCCCGTGACCTTGGTGCTTGTATTGACTGTAGTGCGCGTCATATTAATGCGCAGGTAGCAAAAAGTCACAACATTGCTTTGATATGGAACGTTAAAGATTTCATGTCATTGTCTGAACAACTACGAAAACAAATACGTAGTGCTGCTAAAAAGAATAACTTACCTTTTAAGTTGACATGTGCAACTACTAGACAAGTTGTTAATGTTGTAACAACAAAGATAGCACTTAAGGGTGGTAAAATTGTTAATAATTGGTTGAAGCAGTTAATTAAAGTTACACTTGTGTTCCTTTTTGTTGCTGCTATTTTCTATTTAATAACACCTGTTCATGTCATGTCTAAACATACTGACTTTTCAAGTGAAATCATAGGATACAAGGCTATTGATGGTGGTGTCACTCGTGACATAGCATCTACAGATACTTGTTTTGCTAACAAACATGCTGATTTTGACACATGGTTTAGCCAGCGTGGTGGTAGTTATACTAATGACAAAGCTTGCCCATTGATTGCTGCAGTCATAACAAGAGAAGTGGGTTTTGTCGTGCCTGGTTTGCCTGGCACGATATTACGCACAACTAATGGTGACTTTTTGCATTTCTTACCTAGAGTTTTTAGTGCAGTTGGTAACATCTGTTACACACCATCAAAACTTATAGAGTACACTGACTTTGCAACATCAGCTTGTGTTTTGGCTGCTGAATGTACAATTTTTAAAGATGCTTCTGGTAAGCCAGTACCATATTGTTATGATACCAATGTACTAGAAGGTTCTGTTGCTTATGAAAGTTTACGCCCTGACACACGTTATGTGCTCATGGATGGCTCTATTATTCAATTTCCTAACACCTACCTTGAAGGTTCTGTTAGAGTGGTAACAACTTTTGATTCTGAGTACTGTAGGCACGGCACTTGTGAAAGATCAGAAGCTGGTGTTTGTGTATCTACTAGTGGTAGATGGGTACTTAACAATGATTATTACAGATCTTTACCAGGAGTTTTCTGTGGTGTAGATGCTGTAAATTTACTTACTAATATGTTTACACCACTAATTCAACCTATTGGTGCTTTGGACATATCAGCATCTATAGTAGCTGGTGGTATTGTAGCTATCGTAGTAACATGCCTTGCCTACTATTTTATGAGGTTTAGAAGAGCTTTTGGTGAATACAGTCATGTAGTTGCCTTTAATACTTTACTATTCCTTATGTCATTCACTGTACTCTGTTTAACACCAGTTTACTCATTCTTACCTGGTGTTTATTCTGTTATTTACTTGTACTTGACATTTTATCTTACTAATGATGTTTCTTTTTTAGCACATATTCAGTGGATGGTTATGTTCACACCTTTAGTACCTTTCTGGATAACAATTGCTTATATCATTTGTATTTCCACAAAGCATTTCTATTGGTTCTTTAGTAATTACCTAAAGAGACGTGTAGTCTTTAATGGTGTTTCCTTTAGTACTTTTGAAGAAGCTGCGCTGTGCACCTTTTTGTTAAATAAAGAAATGTATCTAAAGTTGCGTAGTGATGTGCTATTACCTCTTACGCAATATAATAGATACTTAGCTCTTTATAATAAGTACAAGTATTTTAGTGGAGCAATGGATACAACTAGCTACAGAGAAGCTGCTTGTTGTCATCTCGCAAAGGCTCTCAATGACTTCAGTAACTCAGGTTCTGATGTTCTTTACCAACCACCACAAACCTCTATCACCTCAGCTGTTTTGCAGAGTGGTTTTAGAAAAATGGCATTCCCATCTGGTAAAGTTGAGGGTTGTATGGTACAAGTAACTTGTGGTACAACTACACTTAACGGTCTTTGGCTTGATGACGTAGTTTACTGTCCAAGACATGTGATCTGCACCTCTGAAGACATGCTTAACCCTAATTATGAAGATTTACTCATTCGTAAGTCTAATCATAATTTCTTGGTACAGGCTGGTAATGTTCAACTCAGGGTTATTGGACATTCTATGCAAAATTGTGTACTTAAGCTTAAGGTTGATACAGCCAATCCTAAGACACCTAAGTATAAGTTTGTTCGCATTCAACCAGGACAGACTTTTTCAGTGTTAGCTTGTTACAATGGTTCACCATCTGGTGTTTACCAATGTGCTATGAGGCCCAATTTCACTATTAAGGGTTCATTCCTTAATGGTTCATGTGGTAGTGTTGGTTTTAACATAGATTATGACTGTGTCTCTTTTTGTTACATGCACCATATGGAATTACCAACTGGAGTTCATGCTGGCACAGACTTAGAAGGTAACTTTTATGGACCTTTTGTTGACAGGCAAACAGCACAAGCAGCTGGTACGGACACAACTATTACAGTTAATGTTTTAGCTTGGTTGTACGCTGCTGTTATAAATGGAGACAGGTGGTTTCTCAATCGATTTACCACAACTCTTAATGACTTTAACCTTGTGGCTATGAAGTACAATTATGAACCTCTAACACAAGACCATGTTGACATACTAGGACCTCTTTCTGCTCAAACTGGAATTGCCGTTTTAGATATGTGTGCTTCATTAAAAGAATTACTGCAAAATGGTATGAATGGACGTACCATATTGGGTAGTGCTTTATTAGAAGATGAATTTACACCTTTTGATGTTGTTAGACAATGCTCAGGTGTTACTTTCCAAAGTGCAGTGAAAAGAACAATCAAGGGTACACACCACTGGTTGTTACTCACAATTTTGACTTCACTTTTAGTTTTAGTCCAGAGTACTCAATGGTCTTTGTTCTTTTTTTTGTATGAAAATGCCTTTTTACCTTTTGCTATGGGTATTATTGCTATGTCTGCTTTTGCAATGATGTTTGTCAAACATAAGCATGCATTTCTCTGTTTGTTTTTGTTACCTTCTCTTGCACAAGTGTTTGTTTATGCAATCCAGTTTTGTTCTCCTTGATGCAAATAGAGTGATTCTACATTCTTTGACTACTCCGAAGATTATGAAGATACTAAACTAAATGAACTTCAGAAAATTTCTCCACTTTTGAACTGGATATAGATGAAATGTTTACGGTTTGAAGACAAAGGAACTGTAGCCTTGGCCAAACAGGATGATCAAATGGATTGCCCTCATAACCAAAAGAACATGTCCATGGAGATGGAAAGTCTTTTTTTTAACATGAATTTTTAAGTTTATTTGGTGATGAAATAAAAGGTAGATTTTTTTTGTATTTGCCTAATGTATTTTATCAATTTCATCTCACAGTAGCTTCAAAAAAAAGTCCAAATTCAATTTTATGTATTTATTTTTTAAATACATTTATATTTGGCAAAAATATTAAAGTTTTATTTTGATGTCCATTAGGGAAGCAAAATATATATTTTTCTAACCATAAAATGAATGTAAGTGACTCTCACTTGATGGACCAAAGAAAAACAAATTTTTAAAAAGAATGTATATGTTTAAAAAAAGTAAAATAGGCTTGAAATAAATGAATTAACATAATTATGTACCATCTAACTTCTCTATAGTTTGTCTCCAGTGGTGTTTATAAAGTGATGTGCATGTGATGTTGAACAACCCATTTTTATTATTGGAATTTTTATGCTAATGTAAGAACAAATTTAGTAACGTTATTTGTTATTTCTCTAAATTTTCTGAAATGATTTTTTAAAAATGTTTATTTAAAAAAGAGATGGTATTTTTTTTGTAATAACATGTTTAAGACCAAACTTTTATTTAACTTTAAAGTTGGTTTTTCACCTAACGAGATTGGGTGTTATTCTTATAGTTGTTTATAAGTTGCTTTAAAGGGATATTTTGAAAAGTAATTTGAGCAGAAGTATTGATGTTCCACATTTAGCTCATTTATTCATTAGTGTTTTTTGAAAATTTTACAATTTGTTTAACACCAACTTTTAGGGTTAATGGAATAACCAAAGAACAAGGATTTTGAGTTCTTAACTCTCCATGTTTTTTTACACCTTCCACTGTTTTGTACAATTGTGTTTGGCATTAAATTGATGATAAACTTACAGCACAGGGTGATTTCTTTTTTTTTATCCAAACTATACCAGATAACCACCAGCTGGAGTCGTTCTTGATAACGTCACTTTTGATGTTTGGCTCTAACTATCATCCAGAATCACAAGGTTACAGTTTAGAACATGTTAACCTTTATGATGAAGTAATATGTAGTGTACAGCAGTATTGTACGGCAGGCAATCCACAAGCTGTATGTTAACAGATCTACGTGAAAAGAACTGACGGATGTACCAGTCTTCCACGTATGGAGGTTGTATGATGATGGTATTCAAAATTTAAACCTGTATCGAAAACTTGAGTTGTTTTATAATAAATTGATCAACTCTACCCCACAGTTTTACCACTTGAATTCTGGTGCTATAAACATGGTACAACAAACCATATTTTAAGCAAGTCCAAAGGTGATAATGTGTGTTTTTAATATTAACATGCAGACCATTCACCACGTTGAAAATCCCATGTTTGTAAATAGTAATGGAGTTTGCATAGCTTTTGCAAATAATTTGGAAGGAAATGGCCACAACAACAATCAGTGACAAAGTTAGAGTGATAGTAGAAAAATTACATTTTATAAGTTAAATGATGTGGAAGAAGTAATTAAATTGGCTAGTCAAGTAAAGCCTCTACCAGAAGAGAGGACAAGAAATCTACCCTAAGTTTTGTCGAGAAATAACCTTTAAGGGGAGTTGTAAAGTTTAACGTGATCACCTGTTATAAAATGGAGCTCAACTAAACAAACAAACGAGCCCCATTTTTTCATCAGATGGGTGTGTTGTATCTGACCTGTGGGCCCACAAAATCTTTAGGATTTCTCTCTTTTCAAAATTTAAGATTGAATTATATTGATAAAAAAATACATTTGGAGATATTCCGGAAACAGAGCCGTCATAGGGGTCCCACGGGAAGATATTTCCAAGAATCCTTTCTTGGTCCTATTAATCGTTTGCAGAAAAAGCCCTACGAATTCCCCTGAAGGATGATGTTTGCTAAATACCTTGACAGTGTTAAATCGTACCCGAAAGCAAGTTTTAATTTTTTTATTGTATGATGGTTTTTTAAATTTTTTATTTATCAAGGTATCAATAATAATGTTGATGATATAGCATTACTAATTAAGTAACAATAATTATTTAAATGAACGTGAAAAAAAAAGGAATTTACTTTAAATTGTCATCTTATAAAATGAAAAACAGAAACAATGTCACAATTTAAAAGATAACGTAATTCTTTGGTGGCAATATAAGTGATAACTTAGTAGCAGTGCATTTAAAGGAGAGTATAAGGTTAATGAGTCAGAGGCCTATTTAAAGGAGATGTCATTACAGCAATATACGGGACATTTATATCACATTATTTACGTTATACATTAAAATTTGAGGATCTAAAAGATATAGAAATTAGAGACACCTTTTGAAACAAAACCAGCAGATTCATGTGGATAAAATGGGGGAAATCATCTTTTACTACACCACACTATTCTTATATACATACTAGAGTCAAAACTAATATAACAAAGACAGTTGATATTTATGAGACTCTGGGATGAAAGTTGGGAAGAAATGCAGCGAGGCCCCAAATGGGGATAAAAAGTAGAACCCACAACTTTTCCACACTTTTTCTTATACTTGATTCTATTAAAGAACAGATCTATGATAAATTTTCGCTTCATTCTTGTTTAACTTGGTGATTTCTGTGCTAAAAACAATGAAAAATGGTTACGTTCTTTGCTTTCTCTGTATGATGGCCACATTTATATTCCTCTCTCTAAAGTTCTTGTGCCCATATCCACCAATAGAGATTTTCTTATAATTGTATAAGTAAAGAATAAGGGATTTCTGTTCAAACCCAACCTTGAACAGTGGATAATAATGGAAGAACAAAAAGTCGATCAAAACATAGTCAAACCTTCCCCAATCACTCTAATTTTCTGAATTTAACTTTTAAGTGGTGCTTCCATCAACTTTTCATAGCTATACCAAAATAAGCCTTTTCCAACTATTTGCAGGGGAGAGTCGAATCCCTTCCTGGATAAGAAATGTTAAAGAAGTACCAACTTTACATAAGAGGAGGTATGGGATCATAAGTGGAAACAACGTTGTATACCTAAGACATTCAACTTTTCACTAGACTAATTTAACAGAGATAACAAGGAGATATGAATAAAGAACATTTTCATGATCAATAGGGAATATTTTTAAAATATGATAAACCTGTCATTTCCGCTCTAAATTAAAACAAGACAAGGCTAAACCACTTGAGGGTACGGATACGTAAAGAAATTTCAAATCGATGGAAGTATTTAGGGTTTTGGTGATAGAGCTTTAGGACAGGAAATGGAAAACATTTCTAAGGATAAAGATTTTGTGTGTTTCAACCTGGGAGCTCTTAGATTCCGATTGGTAAATACTTCCAAAAGCTCTTACCCAAACGGGATTGTATACAAATGGGATATGAAAGCATGGAACTCTGTATAAGAAACCCAAAGGCTGTAAACATTTCTAAGAGATAAAGATTTTGTGTGTTTCAATCTGGGAGCTCTTAGATACCAATTGGAAAATACTTGTGATTAGCACTTAAGGGGCGATTGTATACAAATGGGATATGAAAGCATGGAACTCTGTATAAGAAACCCAAAGGCTGTAAACATTTCTAAGAGATAAAGATTTTGTGTGTTTCAATCTGGGAGCTCTTAGATACCAATTGGAAAATACTTGTGATTAGCACTTAAGGGGCGATTGTATACAAATGGGATATGAAAGCATGGAACTCTGTATAAGAAACCCAAAGGCTGTAAACATTTCCAA"""

        file_path = temp_workspace / "reference.fasta"
        file_path.write_text(content)
        return file_path

    def test_varvamp_to_artic_conversion(self, temp_workspace, varvamp_test_file):
        """Test complete VarVAMP to ARTIC conversion workflow."""
        output_dir = temp_workspace / "output"

        converter = PrimerConverter()

        # Convert VarVAMP to ARTIC format
        result = converter.convert(
            input_file=varvamp_test_file,
            output_dir=output_dir,
            input_format="varvamp",
            output_formats=["artic"],
            prefix="SARS-CoV-2",
        )

        # Verify conversion results
        assert "artic" in result
        artic_file = result["artic"]
        assert artic_file.exists()

        # Verify ARTIC file content
        content = artic_file.read_text()
        lines = content.strip().split("\n")

        # Should have 6 lines (3 amplicons * 2 primers each)
        assert len(lines) == 6

        # Check that all lines have correct ARTIC BED format (7 fields including sequence)
        for line in lines:
            fields = line.split("\t")
            assert (
                len(fields) == 7
            )  # ARTIC BED format: chrom, start, end, name, pool, strand, sequence
            assert fields[0] == "SARS-CoV-2"  # Reference name
            assert int(fields[1]) < int(fields[2])  # Start < Stop
            assert fields[5] in ["+", "-"]  # Valid strand
            assert len(fields[6]) > 0  # Sequence should not be empty

    def test_artic_to_fasta_conversion(self, temp_workspace, artic_test_file):
        """Test ARTIC to FASTA conversion workflow."""
        output_dir = temp_workspace / "output"

        converter = PrimerConverter()

        # Convert ARTIC to FASTA format
        result = converter.convert(
            input_file=artic_test_file,
            output_dir=output_dir,
            input_format="artic",
            output_formats=["fasta"],
            prefix="nCoV-2019",
        )

        # Verify conversion results
        assert "fasta" in result
        fasta_file = result["fasta"]
        assert fasta_file.exists()

        # Verify FASTA file content
        content = fasta_file.read_text()

        # Should contain FASTA headers
        assert content.count(">") == 6  # 6 primers
        assert "MN908947.3_1_LEFT" in content
        assert "MN908947.3_1_RIGHT" in content

    def test_multi_format_conversion(self, temp_workspace, varvamp_test_file):
        """Test conversion to multiple output formats."""
        output_dir = temp_workspace / "output"

        converter = PrimerConverter()

        # Convert to multiple formats
        result = converter.convert(
            input_file=varvamp_test_file,
            output_dir=output_dir,
            output_formats=["artic", "fasta", "varvamp"],
            prefix="multi_test",
        )

        # Verify all formats were created
        assert "artic" in result
        assert "fasta" in result
        assert "varvamp" in result

        for format_name, file_path in result.items():
            assert file_path.exists()
            assert file_path.stat().st_size > 0  # Not empty

    def test_configuration_integration(self, temp_workspace, varvamp_test_file):
        """Test integration with enhanced configuration system."""
        output_dir = temp_workspace / "output"

        # Create enhanced configuration
        from preprimer.core.enhanced_config import (
            OutputSettings,
            ParserSettings,
            ValidationSettings,
        )

        config = EnhancedConfig(
            validation=ValidationSettings(enabled=True, min_length=20, max_length=30),
            output=OutputSettings(formats=["artic", "fasta"], force_overwrite=True),
            parser=ParserSettings(default_pool=1),
        )

        converter = PrimerConverter(config)

        # Convert with configuration
        result = converter.convert(
            input_file=varvamp_test_file, output_dir=output_dir, prefix="config_test"
        )

        # Verify configuration was applied
        assert len(result) == 2  # Only artic and fasta formats
        assert "artic" in result
        assert "fasta" in result

    def test_error_handling_integration(self, temp_workspace):
        """Test error handling across the system."""
        converter = PrimerConverter()

        # Test with non-existent file
        with pytest.raises((PrePrimerError, ParserError)):
            converter.convert(
                input_file=temp_workspace / "nonexistent.tsv",
                output_dir=temp_workspace / "output",
            )

        # Test with invalid format file
        invalid_file = temp_workspace / "invalid.tsv"
        invalid_file.write_text("This is not a valid primer file")

        with pytest.raises((PrePrimerError, ValidationError)):
            converter.convert(
                input_file=invalid_file, output_dir=temp_workspace / "output"
            )

    def test_registry_integration(self, temp_workspace):
        """Test parser and writer registry integration."""
        # Test parser registry
        parser_registry = ParserRegistry()
        parser_registry.register(VarVAMPParser)
        parser_registry.register(ARTICParser)

        formats = parser_registry.list_formats()
        assert "varvamp" in formats
        assert "artic" in formats

        # Test format detection with proper VarVAMP data
        varvamp_data = """amplicon_name	amplicon_length	primer_name	pool	start	stop	seq	size	gc_best	temp_best	mean_gc	mean_temp	score
test_amp	300	FW_test	1	100	120	ATCGATCGATCGATCGATCG	20	0.5	60.0	0.52	58.5	85.2
test_amp	300	RW_test	1	380	400	CGATCGATCGATCGATCGAT	20	0.5	60.0	0.52	58.5	85.2"""

        test_file = temp_workspace / "test.tsv"
        test_file.write_text(varvamp_data)

        detected_format = parser_registry.detect_format(test_file)
        assert detected_format == "varvamp"

    def test_concurrent_operations(self, temp_workspace, varvamp_test_file):
        """Test concurrent conversion operations."""
        import threading

        output_dirs = [temp_workspace / f"output_{i}" for i in range(3)]
        results = []
        errors = []

        def convert_worker(worker_id):
            try:
                converter = PrimerConverter()
                result = converter.convert(
                    input_file=varvamp_test_file,
                    output_dir=output_dirs[worker_id],
                    output_formats=["artic"],
                    prefix=f"worker_{worker_id}",
                )
                results.append(result)
            except Exception as e:
                errors.append(e)

        # Start multiple conversion threads
        threads = []
        for i in range(3):
            thread = threading.Thread(target=convert_worker, args=(i,))
            threads.append(thread)
            thread.start()

        # Wait for completion
        for thread in threads:
            thread.join(timeout=10)

        # Verify results
        assert len(errors) == 0, f"Errors occurred: {errors}"
        assert len(results) == 3

        # Verify each conversion produced valid output
        for result in results:
            assert "artic" in result
            assert result["artic"].exists()


class TestSystemLimits:
    """Test system limits and edge cases."""

    def test_large_dataset_handling(self, tmp_path):
        """Test handling of large datasets."""
        # Create a large VarVAMP dataset
        num_amplicons = 1000
        header = "amplicon_name\tamplicon_length\tprimer_name\tpool\tstart\tstop\tseq\tsize\tgc_best\ttemp_best\tmean_gc\tmean_temp\tscore\n"

        lines = [header]
        for i in range(num_amplicons):
            amp_name = f"amplicon_{i}"
            lines.append(
                f"{amp_name}\t300\tFW_{i}\t{i%10+1}\t{100+i*400}\t{120+i*400}\tATCGATCGATCGATCGATCG\t20\t0.5\t60.0\t0.52\t58.5\t85.2\n"
            )
            lines.append(
                f"{amp_name}\t300\tRW_{i}\t{i%10+1}\t{380+i*400}\t{400+i*400}\tCGATCGATCGATCGATCGAT\t20\t0.5\t60.0\t0.52\t58.5\t85.2\n"
            )

        large_file = tmp_path / "large_dataset.tsv"
        large_file.write_text("".join(lines))

        # Test parsing large dataset
        parser = VarVAMPParser()
        amplicons = parser.parse(large_file, "large_test")

        assert len(amplicons) == num_amplicons
        assert all(len(amp.primers) == 2 for amp in amplicons)

    def test_memory_usage_patterns(self, tmp_path):
        """Test memory usage patterns with various dataset sizes."""
        import sys

        sizes = [10, 100, 500]
        memory_usage = []

        for size in sizes:
            # Create dataset of specified size
            header = "amplicon_name\tamplicon_length\tprimer_name\tpool\tstart\tstop\tseq\tsize\tgc_best\ttemp_best\tmean_gc\tmean_temp\tscore\n"
            lines = [header]

            for i in range(size):
                lines.append(
                    f"amp_{i}\t300\tFW_{i}\t1\t{100+i*50}\t{120+i*50}\tATCGATCGATCGATCGATCG\t20\t0.50\t60.0\t0.50\t60.0\t95.0\n"
                )
                lines.append(
                    f"amp_{i}\t300\tRW_{i}\t1\t{130+i*50}\t{150+i*50}\tCGATCGATCGATCGATCGAT\t20\t0.50\t60.0\t0.50\t60.0\t95.0\n"
                )

            test_file = tmp_path / f"test_{size}.tsv"
            test_file.write_text("".join(lines))

            # Measure memory before parsing
            import gc

            gc.collect()

            # Parse and measure
            parser = VarVAMPParser()
            amplicons = parser.parse(test_file, f"test_{size}")

            # Verify parsing succeeded
            assert len(amplicons) == size
            memory_usage.append(sys.getsizeof(amplicons))

        # Memory usage should scale reasonably with dataset size
        assert memory_usage[1] > memory_usage[0]  # 100 > 10
        assert memory_usage[2] > memory_usage[1]  # 500 > 100

    def test_extreme_inputs(self, tmp_path):
        """Test handling of extreme input cases."""
        parser = VarVAMPParser()

        # Test empty file
        empty_file = tmp_path / "empty.tsv"
        empty_file.write_text("")

        with pytest.raises(Exception):  # Should fail gracefully
            parser.parse(empty_file, "empty")

        # Test file with only headers
        header_only = tmp_path / "header_only.tsv"
        header_only.write_text("amplicon_name\tprimer_name\tseq\n")

        with pytest.raises(Exception):  # Should fail gracefully
            parser.parse(header_only, "header_only")

        # Test very long sequences
        long_seq = "A" * 10000
        long_seq_file = tmp_path / "long_seq.tsv"
        content = f"amplicon_name\tprimer_name\tseq\tstart\tstop\tpool\namp1\tprimer1\t{long_seq}\t1\t10001\t1\n"
        long_seq_file.write_text(content)

        # Should handle or fail gracefully
        try:
            amplicons = parser.parse(long_seq_file, "long_seq")
            if amplicons:  # If parsing succeeds
                assert len(amplicons[0].primers[0].sequence) == 10000
        except Exception:
            # Graceful failure is acceptable for extreme inputs
            pass
