name: Test Preprimer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -e .  # install the preprimer package
        pip install -r requirements.txt  # Ensure pytest is listed here

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.12'  # Replace with your Python version

    - name: Install mamba and environment dependencies
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install mamba -n base -c conda-forge
        mamba create -n preprimer me-pcr exonerate
        source activate preprimer  # Activate the environment
        python -m pytest tests/test_convert.py  # Run the tests within the environment
