"""
Official primerscheme format writer following primal-page specification.

Generates primer.bed + reference.fasta + info.json structure compatible with:
- primalscheme3 (https://github.com/artic-network/primalscheme3)
- primerscheme-specs (https://github.com/artic-network/primerscheme-specs)
- amplicon-nf (https://github.com/nf-core/amplicon-nf)
"""

import logging
import re
import shutil
from pathlib import Path
from typing import List, Optional, Union

from ..core.exceptions import OutputError
from ..core.interfaces import AmpliconData, OutputWriter
from ..core.primerscheme_info import generate_info_json

logger = logging.getLogger(__name__)


class ARTICWriter(OutputWriter):
    """Writer for official primerscheme format (primalscheme3 compatible)."""

    @classmethod
    def format_name(cls) -> str:
        return "artic"

    @classmethod
    def file_extension(cls) -> str:
        return "primer.bed"  # Official filename from primerscheme-specs

    def write(
        self,
        amplicons: List[AmpliconData],
        output_path: Union[str, Path],
        prefix: str = "",
        **kwargs,
    ) -> Optional[Path]:
        """
        Write amplicon data in official primerscheme format.

        Creates directory structure:
        output_path/
        ├── primer.bed          # 0-based BED format primers
        ├── reference.fasta     # Reference genome sequence
        └── info.json          # Scheme metadata (primal-page schema)
        """
        output_path = self.validate_output_path(output_path)

        # Extract parameters
        prefix = prefix or kwargs.get("prefix", "primers")
        reference_path = kwargs.get("reference_path")

        # BED column count: 7 = PrimalScheme-like (sequence appended), the
        # default; 6 = canonical primal-page / legacy primer.bed (no sequence).
        bed_columns = kwargs.get("bed_columns", 7)

        # Scheme metadata: explicit kwargs win; otherwise fall back to metadata
        # imported from a source scheme's info.json (G2), then to defaults.
        imported = {}
        if amplicons and amplicons[0].metadata.get("scheme_info"):
            imported = amplicons[0].metadata["scheme_info"]

        def meta(key, default):
            if key in kwargs:
                return kwargs[key]
            if imported.get(key):
                return imported[key]
            return default

        schemeversion = meta("schemeversion", "v1.0.0")
        species = meta("species", "Unknown species")
        authors = meta("authors", ["PrePrimer"])
        description = meta("description", "Primer scheme generated by PrePrimer")
        collections = meta("collections", [])

        # Calculate target amplicon size from data
        amplicon_sizes = []
        for amplicon in amplicons:
            if amplicon.length:
                amplicon_sizes.append(amplicon.length)

        ampliconsize = (
            int(sum(amplicon_sizes) / len(amplicon_sizes)) if amplicon_sizes else 400
        )

        # Clean schemename to follow specification
        schemename = self._clean_schemename(prefix)

        # Create official primerscheme directory structure
        scheme_dir = output_path.parent
        primer_bed_file = scheme_dir / "primer.bed"
        reference_fasta_file = scheme_dir / "reference.fasta"
        info_json_file = scheme_dir / "info.json"

        logger.info(f"Writing official primerscheme to: {scheme_dir}")

        try:
            # 1. Write primer.bed file (0-based BED format)
            self._write_primer_bed(amplicons, primer_bed_file, bed_columns)

            # 2. Copy reference.fasta if provided
            if reference_path:
                self._copy_reference_fasta(reference_path, reference_fasta_file)
            else:
                # Create minimal reference file
                self._create_minimal_reference(amplicons, reference_fasta_file)

            # 3. Generate info.json with official schema
            info = generate_info_json(
                schemename=schemename,
                schemeversion=schemeversion,
                ampliconsize=ampliconsize,
                species=species,
                primer_bed_path=primer_bed_file,
                reference_fasta_path=reference_fasta_file,
                authors=authors,
                description=description,
                collections=collections,
                algorithmversion="PrePrimer",
                status="draft",
            )

            info.save(info_json_file)

            # Log success
            total_primers = sum(len(a.primers) for a in amplicons)
            logger.info(
                f"Successfully wrote primerscheme '{schemename}' v{schemeversion} with "
                f"{len(amplicons)} amplicons and {total_primers} primers"
            )
            logger.info(f"Files created: primer.bed, reference.fasta, info.json")

            return primer_bed_file

        except Exception as e:
            raise OutputError(f"Failed to write primerscheme format: {e}")

    def _write_primer_bed(
        self, amplicons: List[AmpliconData], bed_file: Path, bed_columns: int = 7
    ) -> None:
        """Write primer.bed in 0-based BED format.

        Args:
            bed_columns: 7 (PrimalScheme-like, sequence appended) or 6 (canonical
                primal-page / legacy primer.bed without the sequence column).
        """
        with open(bed_file, "w") as f:
            for amplicon in amplicons:
                # Track alt indices per direction so alternate primers within an
                # amplicon get unique names (e.g. _LEFT_0, _LEFT_1).
                alt_counts = {"forward": 0, "reverse": 0}
                for primer in amplicon.primers:
                    # The primer.bed columns are:
                    # chrom start(0-based) end(0-based-exclusive) name pool strand [sequence]
                    # The 7th sequence column is the PrimalScheme-like extension.

                    # PrimerData coordinates are stored 0-based (matching BED), so
                    # they are written verbatim. Guard against negative values
                    # defensively (parsers validate start >= 0).
                    bed_start = max(0, primer.start)
                    bed_end = primer.stop  # BED end is exclusive, so this is correct

                    # Use official ARTIC naming convention for compatibility,
                    # with a per-direction alt index to keep names unique.
                    alt = alt_counts.get(primer.direction, 0)
                    artic_name = primer.artic_name_with_alt(alt)
                    if primer.direction in alt_counts:
                        alt_counts[primer.direction] += 1

                    fields = [
                        primer.reference_id,
                        str(bed_start),
                        str(bed_end),
                        artic_name,
                        str(primer.pool or 1),
                        primer.strand,
                    ]
                    if bed_columns >= 7:
                        fields.append(primer.sequence)
                    f.write("\t".join(fields) + "\n")

    def _copy_reference_fasta(
        self, reference_path: Union[str, Path], target_path: Path
    ) -> None:
        """Copy reference FASTA file to scheme directory."""
        reference_path = Path(reference_path)
        if reference_path.exists():
            logger.info(f"Copying reference genome: {reference_path.name}")
            shutil.copy2(reference_path, target_path)
        else:
            logger.warning(f"Reference file not found: {reference_path}")
            # Create empty reference file to satisfy schema
            target_path.touch()

    def _create_minimal_reference(
        self, amplicons: List[AmpliconData], reference_file: Path
    ) -> None:
        """Create minimal reference.fasta file when none provided."""
        if amplicons and amplicons[0].primers:
            reference_id = amplicons[0].primers[0].reference_id or "reference"

            with open(reference_file, "w") as f:
                f.write(f">{reference_id}\n")
                f.write(
                    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n"
                )  # Placeholder sequence

            logger.info(f"Created minimal reference.fasta for scheme validation")
        else:
            reference_file.touch()

    def _clean_schemename(self, prefix: str) -> str:
        """Clean prefix to create valid schemename following primal-page spec."""
        # Convert to lowercase
        schemename = prefix.lower()

        # Replace invalid characters with hyphens
        schemename = re.sub(r"[^a-z0-9-]", "-", schemename)

        # Remove multiple consecutive hyphens
        schemename = re.sub(r"-+", "-", schemename)

        # Remove leading/trailing hyphens
        schemename = schemename.strip("-")

        # Ensure not empty
        if not schemename:
            schemename = "primer-scheme"

        logger.debug(f"Cleaned schemename: '{prefix}' -> '{schemename}'")
        return schemename

    def validate_output_path(self, output_path: Union[str, Path]) -> Path:
        """Validate and create primerscheme directory structure."""
        path = Path(output_path)

        # Ensure we have a directory for the scheme
        scheme_dir = path.parent if path.suffix else path
        scheme_dir.mkdir(parents=True, exist_ok=True)

        return path
